// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportPNG(arg1:string):Promise<string>;

export function GetLaunchOptions():Promise<main.LaunchOptions>;

export function LoadAppSettings():Promise<string>;

export function OpenDotaJSON():Promise<main.FilePayload>;

export function ReadDotaJSON(arg1:string):Promise<main.FilePayload>;

export function ReadReferenceImage(arg1:string):Promise<main.ReferenceImagePayload>;

export function SaveAppSettings(arg1:string):Promise<void>;

export function SaveDotaJSON(arg1:string,arg2:string,arg3:boolean):Promise<string>;
