// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportPNG(arg1) {
  return window['go']['main']['App']['ExportPNG'](arg1);
}

export function GetLaunchOptions() {
  return window['go']['main']['App']['GetLaunchOptions']();
}

export function LoadAppSettings() {
  return window['go']['main']['App']['LoadAppSettings']();
}

export function OpenDotaJSON() {
  return window['go']['main']['App']['OpenDotaJSON']();
}

export function ReadDotaJSON(arg1) {
  return window['go']['main']['App']['ReadDotaJSON'](arg1);
}

export function ReadReferenceImage(arg1) {
  return window['go']['main']['App']['ReadReferenceImage'](arg1);
}

export function SaveAppSettings(arg1) {
  return window['go']['main']['App']['SaveAppSettings'](arg1);
}

export function SaveDotaJSON(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveDotaJSON'](arg1, arg2, arg3);
}
